// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

/**
 * Custom Script Commands
 * Place the definition of custom script commands in this file.
 * Format:
 *	BUILDIN_DEF(command_name,"parameters"),
 **/

//BUILDIN_DEF(example,""),
BUILDIN_DEF(pcblockall,"ii"),
BUILDIN_DEF(issitting,""),
/*BUILDIN_DEF(sitdown,""),
BUILDIN_DEF(standup,""),*/
BUILDIN_DEF(gethotkeys,"?"),
BUILDIN_DEF(updatehotkey,"ivii??"),
BUILDIN_DEF(clearhotkeys,"?"),
BUILDIN_DEF(monster2,"siisiii???"),
BUILDIN_DEF(setbattlegroup,"ii"),
BUILDIN_DEF(getbattlegroup,"i"),
BUILDIN_DEF(checkmap,"s"),